# NOTE: ansible prerequisite variables are in the scripts folder

# setup vars
project:        "automacion"
version:        "1.4.0"

# homebrew vars
homebrew_installed_packages: []
homebrew_cask_apps:
  - keepassxc
  - atom
